/* eslint-disable prettier/prettier */
export const Assuntos = [
  {area:'',frase:'Voce gosta de patos? '},
  {area:'',frase:'O dia está lindo hoje. Você sabe algum lugar bonito da cidade para ir aproveitar o Sol?'},
  {area:'',frase:'Se fosse para escolher um jogo de videogame para você habitar, qual você iria escolher?'},
  {area:'',frase:'Eu gostei muito da roupa que você está usando. Combinou muito com você.'},
  {area:'',frase:'Estou em dúvida em qual bebida tomar, me ajuda a escolher?'},
  {area:'',frase:'Eu queria muito assistir a alguma série de comédia para poder desestressar. Você tem alguma para indicar?'},
  {area:'',frase:'Entre pizza e hambúrguer, qual você escolheria nunca mais poder comer?'},
  {area:'',frase:'Você faz skincare? Sua pele é tão linda!'},
  {area:'',frase:'Eu amei o seu cabelo. Ele é muito bonito.'},
  {area:'',frase:'O que você prefere, ter a cabeça do tamanho de uma bola de tênis ou ter o pescoço da largura de um lápis?'},
  {area:'',frase:'Se as cores tivessem gosto, qual você acha que seria doce e o que seria salgado?'},
  {area:'',frase:'Eu acho o Adam Sandler o melhor ator e é muito injusto ele nunca ter ganhado um Oscar.'},
  {area:'',frase:'Se você tivesse que fazer uma playlist com 5 músicas para ouvir pelo resto da sua vida, quais você escolheria?'},
  {area:'',frase:'Você já parou para pensar como seria engraçado se todos estivessem pelados dentro dessa sala?'},
  {area:'',frase:'Como você acha que o seu melhor amigo te descreveria?'},
  {area:'',frase:'O que aconteceu de interessante no seu dia?'},
  {area:'',frase:'Se você pudesse ter um super poder, qual seria?'},
  {area:'',frase:'Você tem algum talento que a maior parte das pessoas não sabe?'},
  {area:'',frase:'Se você pudesse viajar no tempo, iria para que época?'},
  {area:'',frase:'Se você pudesse conhecer qualquer figura histórica, quem seria?'},
  {area:'',frase:'Qual é a sua comida preferida?'},
  {area:'',frase:'Se pudesse morar em qualquer lugar do mundo, onde seria?'},
  {area:'',frase:'Como é um dia perfeito para você?'},
  {area:'',frase:'Tem feito maratona de séries? '},
  {area:'',frase:'Você gosta de dançar?'},
  {area:'',frase:'O que deixa você muito feliz?'},

]