/* eslint-disable prettier/prettier */
export const Cantadas = [
  
{area:'',frase:'Se você acredita em salvação, teria como você me salvar da solidão? '},
{area:'',frase:'Tinha dois docinhos, o brigadeiro e o beijinho. Comi o brigadeiro e qual sobrou?'},
{area:'',frase:'Eu não sou Casas Bahia, mas prometo dedicação total a você '},
{area:'',frase:'Papo de urubu, pena de galinha, se você quer um beijinho dê uma risadinha'},
{area:'',frase:'Se beleza fosse flor, você seria o Jardim Botânico! '},
{area:'',frase:'Não sou carro, mas sou Para ti.'},
{area:'',frase:'Vou te dar um beijo, se você não gostar me devolve.'},
{area:'',frase:'Nossa, tô sentindo uma dor no peito, espero que seja amor. Porque se for enfarto, eu nunca mais vou ver você...'},
{area:'',frase:' Tá vendo aquela estrela ali? Mandei pendurar pra você.'},
{area:'',frase:' Queria te desejar noite, porque se fosse boa, estaríamos juntos'},
{area:'',frase:' Você não é pescoço mais mexeu com a minha cabeça! '},
{area:'',frase:' Usei shampoo anti-quedas, mas continuo caindo de amores por você'},
{area:'',frase:' Nossa, você foi feita com velas, mel, fitinhas vermelhas e rosas? Porque te achei uma simpatia'},
{area:'',frase:' Crush, um mês atrás eu era apaixonado por você e parece que estamos no mês passado ainda'},
{area:'',frase:' Use aquele shampoo para esquecer o ex, ele chama Euserve'},
{area:'',frase:' Tá calor né? Mas não é de hoje que eu me derreto por você'},
{area:'',frase:' Pesquisas apontam que agente junto é erro de gramática, mas a gente separado é erro do destino'},
{area:'',frase:' O que eu sinto por você é motorista, porque passageiro não é'},
{area:'',frase:' Você sabe o número da polícia? Infelizmente, vou ter que denunciar você por roubar meu coração'},
{area:'',frase:' Nada na vida é perfeito, mas você é o que mais se aproxima da perfeição'},
{area:'',frase:' Não existe amor à primeira vista. O que existe é a pessoa certa, no momento certo. Você por acaso estava lá'},
{area:'',frase:' Existe um vazio no meu coração que tem as suas medidas. Quer entrar?'},
{area:'',frase:' Se preto fosse paixão e branco fosse carinho, o que eu sinto por você seria xadrezinho'},
{area:'',frase:' Não te doem as pernas de fugir dos meus sonhos todas as noites, meu amor?'},
{area:'',frase:' Gosto de seus olhos, porém prefiro os meus, pois se não fosse por eles eu jamais veria os seus...'},
{area:'',frase:' Se toda vez que eu fechar os olhos, ganhasse um beijo seu, fecharia os olhos eternamente! '},
{area:'',frase:' Você acredita em amor à primeira vista ou devo passar por aqui mais uma vez?'},
{area:'',frase:' Sua mãe é uma rosa e seu pai um jasmim, admiro eles porque fizeram você especialmente pra mim'},
{area:'',frase:' Pensei que ia me divertir na internet, mas parece que só cheguei aqui pra sofrer por não ser o amor dessa mulher maravilhosa'},
{area:'',frase:' Você não pode ser o meu primeiro, mas você pode ser meu último'},
{area:'',frase:' As rosas são vermelhas, violetas são azuis, eu não posso rimar, mas posso namorar você?'},
{area:'',frase:' Se você está aqui, quem está gerenciando o céu?'},
{area:'',frase:' Se você segurar 8 rosas na frente de um espelho, você verá 9 das coisas mais bonitas do mundo! '},
{area:'',frase:' Ontem eu queria te beijar. Hoje estou igual ontem'},
{area:'',frase:' Onde é que eu deixo meu currículo para concorrer a vaga de amor da sua vida?'},
{area:'',frase:' Hoje eu vou dormir com Deus. Amanhã, se Deus quiser, eu vou dormir com você'},
{area:'',frase:' Igual você, nem o Google encontra'},
{area:'',frase:' Eu não sou plano de saúde, mas se você quiser eu acabo com a sua carência.'},
{area:'',frase:' Espero que você nao tenha diabetes, porque agora eu fiquei doce, doce, doce, doce! '},
{area:'',frase:' Eu não sou o Luciano Huck, mas eu quero você no meu lar doce lar! '},
{area:'',frase:' Eu não sou Alice, mas com você me sinto no País das Maravilhas'},
{area:'',frase:' Você não é massagem cardíaca, mas toca e reanima o meu coração! '},
{area:'',frase:' Eu perdi o número do meu telefone… Me empresta o seu?'},
{area:'',frase:' Em cima da colina passa boi passa boiada, só saio da sua frente quando for minha namorada.'},
{area:'',frase:' Você não é GPS quebrado, mas me deixa sem rumo…'},
{area:'',frase:' Fica comigo que eu faço esquecer o João. Que João? Viu só, já está esquecendo…'},
{area:'',frase:' Por acaso é seu aniversário? Porque você está de parabéns'},
{area:'',frase:' Por acaso seu pai é pirata? Não, porquê? Porque você é um tesouro'},
{area:'',frase:' Você não é colesterol mais afetou meu coração…'},
{area:'',frase:' Meu amor por você é igual à obra do governo. Nunca acaba…'},
{area:'',frase:' Me passa seu Twitter? É que a minha mãe falou para eu seguir meu sonho! '},
{area:'',frase:' Sabe estacionar? Porque tem uma vaga no meu coração'},
{area:'',frase:' Pressa é sua inimiga, porque eu ouvi dizer que a pressa é inimiga da perfeição'},
{area:'',frase:' Me chama de urna eletrônica e me dá seu voto de confiança'},
{area:'',frase:' Se eu fosse um refrigerante, seria Soda, porque no meu coração soda você'},
{area:'',frase:' Sabe o que combina com você? Eu! '},
{area:'',frase:' Sua mão ficaria mais bonita encaixada na minha'},
{area:'',frase:' Eu queria ser grego, mas grego eu não posso ser, porque grego tem várias deusas e minha única deusa é você'},
{area:'',frase:' Vontade de fazer aquilo que começa com s: ser o amor da sua vida'},
{area:'',frase:' Que tudo na sua vida brilhe como seus olhos, seja maravilhoso como seu coração, e linda como você.'},
{area:'',frase:' Você sabe qual é o motivo do meu sorriso todos os dias? A primeira palavra dessa frase...'},
{area:'',frase:' Meu coração é totalmente seu e às vezes parece pequeno demais para todo amor que sinto por você! '},
{area:'',frase:' Especial é você, que me faz sorrir nos piores momentos'},
{area:'',frase:' Eu juro que eu tinha pensado em uma cantada infalível há um minuto, mas toda vez que eu chego perto de você parece que meu mundo para, eu esqueço de tudo e só consigo me concentrar nos seus olhos.'},
{area:'',frase:' O amor não é mais que poesia cantada pelo coração'},
{area:'',frase:' Já quis o mundo inteiro, mas agora percebo que esse mundo que tanto quis sempre foi você'},
{area:'',frase:' O seu sorriso é tudo que eu quero e uma chance é tudo que preciso'},
{area:'',frase:' Aprendi a tocar violão e até a escrever poesia, descobri onde nascem os mares, a paz, o amor e até a alegria. Hoje eu sei qual a origem da beleza: você.'},
{area:'',frase:' Acabei de tomar o maior susto da minha vida. Por momentos, pensei que tinha morrido e ido para o céu, pois tem um anjo na minha frente.'},
{area:'',frase:' Já imaginei como seria a nossa vida juntos muitas vezes, mas tenho certeza de que nem o mais louco dos sonhos iria se comparar com a realidade de ter você ao meu lado'},
{area:'',frase:' Um dia me perguntaram "O que você viu nela?" e eu respondi "O que faltava em mim! '},
{area:'',frase:' E tem como não sorrir quando me lembro de você?'},
{area:'',frase:' Não sei se o mundo é bom, mas ele ficou muito melhor quando você chegou'},
{area:'',frase:' Fui ver a previsão do tempo e li que vai rolar um clima entre nós'},
{area:'',frase:' Tentando capturar aquele pokemon lendário chamado seu coração'},
{area:'',frase:' Entre Star Wars e Star trek, o que eu queria mesmo era star com você'},
{area:'',frase:' Não sou o Yoshi, mas daria até minha vida por você'},
{area:'',frase:' Desativa esse firewall e deixa eu invadir seu coração'},
{area:'',frase:' Você não é o Charmander, mas me deixa pegando fogo'},
{area:'',frase:' Me chama de Mario e vem ser minha princesa Peach'},
{area:'',frase:' Meu amor é igual ao mapa de Minecraft: infinito e cheio de surpresas'},
{area:'',frase:' Você não é Death Note, mas me matou quando me escreveu pela primeira vez'},
{area:'',frase:' Se você quiser pode até me chamar de Buzz Lightyear, porque eu sou capaz de levar a nossa relação ao infinito e além'},
{area:'',frase:' Você deveria entrar em Hogwarts, porque o que você faz com o meu coração só pode ser bruxaria'},
{area:'',frase:' Se você quiser ser o meu player dois, o lugar está reservado para salvarmos vários jogos no meu coração'},
{area:'',frase:' Não sou o Stephen King, mas meu coração fica iluminado quando você olha pra mim'},
{area:'',frase:' Queria ser o Batman para que você me chamasse sempre que precisasse de alguém, mas já que não possuo batsinal, vem de Zap'},
{area:'',frase:' Você é feito de lítio, neodímio, oxigênio e carbono. Sabe por quê? Porque você é Li-Nd-O-NA'},
{area:'',frase:' Você não é Tesseract, mas é a única pessoa capaz de abrir as portas do meu coração'},
{area:'',frase:' O único intruso que eu quero na minha vida é... Você! '},
{area:'',frase:' Você é um eixo terrestre? Porque meu mundo gira em torno de você! '},
{area:'',frase:' Você é do Mortal Kombat? Porque sua beleza me deu fatality'},
{area:'',frase:' Vem ser o Mario do meu Luigi'},
{area:'',frase:' Eu sei que não sou herói da DC, mas você com certeza é a Mulher Maravilha'},
{area:'',frase:' Eu devo ter tomado um pouco de Felix Felicis… Porque estou com sorte de ter te encontrado! '},
{area:'',frase:' Oi, eu deveria ser chamado de Stark no espaço, pois eu perdi o ar quando eu te vi! '},
{area:'',frase:' Você tem um mapa? Não, por quê? Porque me perdi no brilho dos seus olhos.'},
{area:'',frase:' Havia dois ursos o Beijaeu e o Mebeija e então o Beijaeu morreu. Quem sobrou?'},
{area:'',frase:'Não sou carro, mas sou Para ti.'},
{area:'',frase:'Eu não sou a Casas Bahia, mas prometo dedicação total a você.'},
{area:'',frase:' Seu nome é Tamara né? Não, por quê? Por que você TAMARAvilhosa'},
{area:'',frase:'Você não é pescoço mais mexeu com a minha cabeça!'},
{area:'',frase:'Se você fosse um sanduíche teu nome seria X-Princesa.'},
{area:'',frase:'Eu perdi o número do meu telefone… Me empresta o seu?'},
{area:'',frase:'Você não usa calcinha, você usa porta-jóias'},
{area:'',frase:'me chama de capeta e deixa te possuir'},
{area:'',frase:'Você é o ovo que faltava na minha marmita.'},
{area:'',frase:'papo de urubu, pena de galinha, se você quer um beijinho dê uma risadinha.'},
{area:'',frase:'casando comigo você nunca vai pegar na enxada! Só vai ter que fazer amor desde a manhã até a madrugada!'},
{area:'',frase:'me chama de tabela periódica e diz que rola uma química entre nós.'},
{area:'',frase:'se beleza brotasse em ovos você seria dona da granja inteira!'},
{area:'',frase:'você é sempre gostosa assim ou hoje tá fantasiada de lasanha?'},
{area:'',frase:'você é tão desejada quanto uma sexta-feira!'},
{area:'',frase:'você foi feita com velas, mel, fitinhas vermelhas e rosas? Porque te achei uma simpatia.'},
{area:'',frase:'você não é a Garota de Ipanema, mas é a coisa mais linda e cheia de graça que já vi.'},
{area:'',frase:'Em cima da colina passa boi passa boiada, só saio da sua frente quando for minha namorada.'},
{area:'',frase:'que roupa feia, Tira isso agora!'},
{area:'',frase:'eu não sou o Luciano Huck, Mas eu quero você no meu lar doce lar! Sua linda!'},
{area:'',frase:'você é uma paçoca? Porque só de sentir o cheiro já dá vontade de comer, sua linda!'},
{area:'',frase:'eu rezo 1/3, para achar 1/2 De te levar pra 1/4, sua linda!'},
{area:'',frase:'você não é piso molhado Mas eu já tô pronto, pra te passar o rodo, sua linda!'},
{area:'',frase:'eu pai é dono da Tam?. Não, por que? Então como é que faz pra ter um avião desse em casa?'},
{area:'',frase:'você é o doce de leite Que falta no meu churros.'},
{area:'',frase:'você tem brigadeiro?. Não Então me dá um beijinho.'},
{area:'',frase:'entre Star Wars e Star trek, O que eu queria mesmo era star com você.'},
{area:'',frase:'eu não sou plano de saúde, Mas se você quiser eu acabo com a sua carência.'},
{area:'',frase:'você deve comer photoshop no café da manhã! Pra ser tão linda assim!'},
{area:'',frase:'eu não sou manteiga de cacau, Mas adoraria amaciar seus lábios.'},
{area:'',frase:'seu nome é Camila?. Sim, por que? Então vem camilamber'},
{area:'',frase:'Desculpe, eu não já fiquei com você antes? Não? Vamos dar um jeito nisso.'},
{area:'',frase:'Meu nome e Arnaldo mais pode me chamar de Naldo, pois quando eu te vi perdi o ar.'},
{area:'',frase:'Seu pai é mecânico? Porque você é uma graxinha!'},
{area:'',frase:'a economia grega anda tão ruim assim? Por quê? Porque até uma deusa grega como você veio morar aqui!'},
{area:'',frase:'Nossa, você é tão linda que não caga, lança bombom!'},
{area:'',frase:'Você acredita em amor à primeira vista ou devo passar por aqui mais uma vez?'},
{area:'',frase:'Se felicidade fosse dinheiro, você seria o Banco Central e eu seria o maior investidor.'},
{area:'',frase:'vamos viajar o mundo usando meus créditos de desconto no Airbnb?'},
{area:'',frase:'Me chama de previsão do tempo e diz que tá rolando um clima.'},
{area:'',frase:'Me passa o seu Twitter? O meu pai disse que eu devo seguir o meu sonho.'},
{area:'',frase:'Não sou traficante, mas eu quero a sua boca.'},
{area:'',frase:'Faça uma pose de príncipe declamando um poema e diga: Pulei na água até o umbigo, então, quer ficar comigo?'},
{area:'',frase:'você é tão ue se eu te matar de amor ainda sobram mais 6 vidas.'},
{area:'',frase:'Gosta de história? Vamos começar a nossa?'},
{area:'',frase:'1 minuto são 60 maneiras de pensar em você '},
{area:'',frase:'Quero te beijar de olhos fechados e coração aberto '},
{area:'',frase:'Existe um vazio no meu coração que tem as suas medidas. Quer entrar? '},
{area:'',frase:'Aposto um beijo que você me dá um fora '},
{area:'',frase:'Aposto um beijo que você me dá um fora '},
{area:'',frase:'Me chama de previsão do tempo e diz que tá rolando um clima '},
{area:'',frase:'Faz que nem álbum: cola em mim e me completa '},
{area:'',frase:'sextoou com s de solteiro/solteira mas se você quiser bb pode ser S de seu/sua'},
{area:'',frase:'ei Bb, felicidade não tem preço ,tem o seu nome'},
{area:'',frase:'eu não sou cachoeira, mas tenho quedas por você'},
{area:'',frase:' eu não sou televisão, mas tô ligadão em você'},
{area:'',frase:'você gosta de maionese ou prefere que quetechup?'},
{area:'',frase:' valorize sua mãe pois um dia ela vai ser minha sogra bb'},
{area:'',frase:'sua mãe está de parabéns achei que só a Nestlé fabricava tentação, mas pelo visto ela também'},
{area:'',frase:' troquei de operadora  agora meu plano é você '},
{area:'',frase:'ei Bb, felicidade não tem preçotem o seu nome'},
{area:'',frase:' nem o Waze me tira daqui,  de tão perdido que estou em você.'},
{area:'',frase:'você deve tá muito cansada né? porque você passeou a noite todinha na minha cabeça'},
{area:'',frase:'eu não sou o Luciano Huck, mas quero te levar pro meu lar doce lar'},
{area:'',frase:'sabe porque em baixo da sua cama não tem rato ? pq em cima da cama dorme uma gatinha'},
{area:'',frase:' Eu não sou corda, mas estou amarradão  em você'},
{area:'',frase:'Red Bull te da asas  e eu te dou amor e carinho'},
{area:'',frase:'eu não sou bitcoin, mas investe em mim que eu valorizo'},
{area:'',frase:' oi bb, te desejo sorte pq felicidade é só comigo'},
{area:'',frase:'você não é rebelião de presídio mas deixa meu colchão pegando fogo'},
{area:'',frase:'gata, eu queria ser seu sono   pra te levar pra cama a noite toda'},
{area:'',frase:' você não é choque elétrico, mas eu me arrepio todinho por você'},
{area:'',frase:'Gata, sabe qual a diferença do ferro de passar e da vontade que eu tenho de te pegar ? é que o ferro passa'},
{area:'',frase:'Gata, quantas lâmpadas eu preciso comprar pra deixar claro que eu sou o amor da sua vida!'},
{area:'',frase:'Gata, seu pai é dono da fábrica de margarina ? pq vc é uma delicia'},
{area:'',frase:'cadê o juiz pra marcar essa falta que vc ta me fazendo?'},
{area:'',frase:'me diz uma coisa, se a recomendação é ficar em casa, pq vc tá nos meus pensamentos??'},
{area:'',frase:' você faz aniversário 10 de outubro?  pq você é 10/10'},
{area:'',frase:' você não é auxílio emergencial, mas na primeira oportunidade eu pego Cara sorridente sarcástica'},
{area:'',frase:'Gata, você é gostosa assim msm ou ta fantasiada de Strogonoff??'},
{area:'',frase:'Vc mora em apt? Pq edifício ficar longe de vc'},
{area:'',frase:'seu um beijo vale mais que mil palavras  deixa eu fazer uma redação na sua boca'},
{area:'',frase:'Me chama de Karl Marx e vem fazer revolução na minha cama'},
{area:'',frase:' me chama de fritura  pq eu só tenho óleos pra vc bb'},
{area:'',frase:'Queria ser um envelope,pra você encher de selinhos'},
{area:'',frase:'Não sou câmera, mas meu foco é vc bb'},
{area:'',frase:'gata, seu pai é pipoqueiro ?é que você pra mim parece um estouro'},
{area:'',frase:'gata, meu mapa de pirata tem um "X" em você que é meu tesouro'},
{area:'',frase:'Sou o pedreiro que sua obra necessita'},
{area:'',frase:'Me deixa ser a tampa da sua marmita'},
{area:'',frase:'gata, sou um pedreiro parente, se for pra você minha obra é prima'},
{area:'',frase:'gata, seu corpo é um bagageiro? pq você tá com tudo em cima'},
{area:'',frase:'gata, vôce não é BR 101 mas é um pedaço de mal caminho'},
{area:'',frase:'gata  , me chama uma ambulância é que a suas coxa me causaram um infarto'},
{area:'',frase:'Te achei bonita e interessante, bora fechar?'},





]
