/* eslint-disable prettier/prettier */
export const Senadores = [
{area:'',frase:'Senador Eduardo Braga  '},
{area:'',frase:'Senador Renan Calheiros '},
{area:'',frase:'Senador Ciro Nogueira '},
{area:'',frase:'Senador Omar Aziz '},
{area:'',frase:'Senador Otto Alencar '},
{area:'',frase:'Senador Tasso Jereissati '},
{area:'',frase:'Senador Eduardo Girão '},
{area:'',frase:'Senador Marcos Rogério '},
{area:'',frase:'Senador Jorginho Mello '},
{area:'',frase:'Senador Humberto Costa '},
{area:'',frase:'Senador Randolfe Rodrigues '},
{area:'',frase:'Senador Jader Barbalho '},
{area:'',frase:'Senador Luis Carlos Heinze '},
{area:'',frase:'Senador Angelo Coronel '},
{area:'',frase:'Senador Marcos do Val '},
{area:'',frase:'Senador Zequinha Marinho '},
{area:'',frase:'Senador Rogério Carvalho '},
{area:'',frase:'Senador Alessandro Vieira '},
{area:'',frase:'Senadora Simone Tebet '},
{area:'',frase:'Senadora Eliziane Gama '},
{area:'',frase:'Senadora Soraya Thronicke'},
/*
{area:'',frase:'Elcio Franco, ex-secretário do Ministério da Saúde'},
{area:'',frase:'Arthur Weintraub, ex-assessor da Presidência'},
{area:'',frase:'Carlos Wizard, empresário'},
{area:'',frase:'Eduardo Pazuello, ex-ministro da Saúde'},
{area:'',frase:'Ernesto Araújo; ex-ministro das Relações Exteriores'},
{area:'',frase:'Fabio Wajngarten; ex-secretário de Comunicação'},
{area:'',frase:'Francieli Fantinato; coordenadora do Programa nacional de Imunização'},
{area:'',frase:'Hélio Angotti Neto, secretário de Ciência, Tecnologia, Inovação e Insumos Estratégicos do Ministério da Saúde'},
{area:'',frase:'Marcellus Campêlo, ex-secretário de Saúde do Amazonas'},
{area:'',frase:'Marcelo Queiroga, ministro da Saúde'},
{area:'',frase:'Mayra Pinheiro; secretária de gestão e trabalho do Ministério da Saúde'},
{area:'',frase:'Nise Yamaguchi, médica'},
{area:'',frase:'Paulo Zanoto, médico'},
{area:'',frase:'Luciano Dias Azevedo, médico anestesista'}*/
]