/* eslint-disable prettier/prettier */
export const Whatsapps = [
  {area:'',frase:'Parado 😵😵😶😯✋🏻 você foi multado 🤠😎👮🏻‍♀️👮🏻‍♀️💰 e o valor 😢🤢😱🤑😱 é os 9 números do seu ZAP 😋😋😋🤫🤫 mais o DDD 😈😈📞📲📲  😍🤩🤩🤪 passa zap 😎👻😻'},
  {area:'',frase:'PI PIPI⚠️ ⚠️ PIPIPIIII⚠️ ⚠️PIPIPIPIPI⚠️ PARADA AI ✋ VOCÊ ACABOU DE RECEBER UMA MULTA O seu delito foi SER GOSTOSA DEMAIS❗️❗️❗️ VALOR DA MULTA: 11Os 11 número do seu ZAP ZAP. 😙🤙 😍😘 ESTOU NO AGUARDO.'},
  {area:'',frase:'zap ao contrário é paz se vc é a favor da paz passa o zap'},
  {area:'',frase:'nao passou em medicina? 😱😥😓 nao passou em direito? 😱😥😓 nem psicologia? 😱😥😓  calma ai 🤚😆🙏 nada esta perdido 👍🙏 vc ainda pode passar o zap kkkkkkkkkkkkkkkk 🤣🤣🤣  Pv liberado linda 😳😳🤫🤫'},
  {area:'',frase:'velocidade 🏃🏃🏃🚌 escalar 🙊✅👍 média 👍👍😂 💫💫 de 💫💫 zero 🌚🔴🔴🚫😪 a derivada se for constante😎🌀 pegou?😍😍 entao vem de zap 😂😂👌💯'},
  {area:'',frase:'Meu nome é Optimus ZAP Líder dos Autozap. Vem de mundo longe para solicitar seu Zap'},
  {area:'',frase:'🚨🚨Piuuuu ✋👮‍♂️Parado Aí✋✋ Vc Esta Sendo quarentenado👀👀Na 🚔Operaçao CoZap19🦠😷📱 Passa Pra Ca👋 Seu Zap😂 Para Que Possamos Resolver😘 Isso😘😘😍😍👊👊👌✌️✌️❤️❤️👩‍⚕️🧑‍⚕'},
  {area:'',frase:'VEM DE ZAP EM INGLÊS: COMES FROM ZAP 😏📲😍🗽'},
  {area:'',frase:'VEM DE ZAP EM ÁRABE: يأتي من انطلق👳📲👀🕌'},
  {area:'',frase:'VEM DE ZAP EM AMÁRICO: የሚመጣው😍😏📲'},
  {area:'',frase:'VEM DE ZAP EM ALBANÊS: vjen nga zap-it😍😏📲'},
  {area:'',frase:'VEM DE ZAP EM JAPONÊS: ザップから来ています🍣😏📲'},
  {area:'',frase:'VEM DE ZAP EM COREANO: 에서 온다😏📲💣'},
  {area:'',frase:'VEM DE ZAP EM ESPANHOL: proviene de zap 💦🐃📲😏'},
  {area:'',frase:'VEM DE ZAP EM ALEMÃO: kommt von zap卍卍😏😏📲'},
  {area:'',frase:'VEM DE ZAP EM GREGO: προέρχεται από 🤗👼😏📲'},
  {area:'',frase:'VEM DE ZAP EM FRANCÊS: vient de zap📲🗼'},
  {area:'',frase:'VEM DE ZAP EM CHINÊS: 來自😏📲🏯🎏'},
  {area:'',frase:'VEM DE ZAP EM HAVAIANO: hele mai ana mai ka zap🏝🌋😍📲😏'},
  {area:'',frase:'VEM DE ZAP EM SUECO: kommer från zap❄️❄️😏📲'},
  {area:'',frase:'MANDA TAMBÉM UM PRA GATINHA HACKER:💻 01110110 01100101 01101101 00100000 01100100 01100101 00100000 01111010 01100001 01110000  📲😏'},
  {area:'',frase:'VEM DE ZAP EM BRAILE: ..·.::..:···.:.··.·::.·.:····::..'},
  {area:'',frase:'QUAL SUA DESCULPA PRA NÃO IR DE ZAP❔❓'},
  {area:'',frase:'APROVEITA E CHAMA LÁ NO ZAP 👉👉A SENHA É: OI BB 😍😍'},
  {area:'',frase:'Você conhece os terra-zapistas? São pessoas que acreditam que a terra é um grande zap zap👌👌👌👌 VEM DE ZAP'},
  {area:'',frase:'Opa opa, paradinha ai, vai passando esse teu ZAP e ninguém se machuca👌😎'},
  {area:'',frase:'⚠️ A 🌐 ONU 🌐 VAI INCLUIR NA CARTA ✉️ DE DIREITOS HUMANOS MAIS UM DIREITO ⚠️ 👀👩‍👩‍👧‍👧👀 DIREITO DE IR 👉 E VIR 👈 DE ZAP 💬🔥 VEM DE ZAP 💬🔥'},
  {area:'',frase:'Parado 😵😵😶😯✋🏻 você foi multado 🤠😎👮🏻‍♀️👮🏻‍♀️💰 e o valor 😢🤢😱🤑😱 é os 9 números do seu ZAP 😋😋😋🤫🤫 mais o DDD 😈😈📞📲📲 '},
  {area:'',frase:'😍🤩🤩🤪 passa zap 😎👻😻'},
]